# Site settings
title: Marc Beepath
tag_text: Marc Beepath
description: Marc Beepath is a Software Engineer based in the UK from Trinidad & Tobago.
url: "https://marc.tt"
lang: "en"
author: "Marc Beepath"
email: "hi@marc.tt"
github: "marcbeep"
linkedin: "marcbeep"
youtube: "@MarcBeepath"

# Build settings
markdown: kramdown
exclude: ["README.md", "node_modules", "package.json", "package-lock.json"]
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
    permalink: /:path/
  films:
    output: true
    permalink: /:path/

# Sitemap Configuration
sitemap:
  changefreq: weekly
  priority: 0.8
  exclude:
    - /404.html
    - /assets/**/*
    - /css/**/*
    - /js/**/*
    - /images/**/*
    - /favicons/**/*
  include:
    - /projects/**/*
    - /writings/**/*
    - /films/**/*

# Compression and optimization
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: development

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Marc Beepath"
      comments: false
      share: true
      keywords: "software engineering, AI, fintech, startups, technology, personal blog"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"
      author: "Marc Beepath"
  -
    scope:
      path: ""
      type: "films"
    values:
      layout: "films"
      author: "Marc Beepath"
