# Site settings
title: Marc Beepath
tag_text: Marc Beepath's personal website, written in markdown.
description: Marc Beepath is a Software Engineer based in the UK from Trinidad & Tobago.
url: "https://marcbeep.com"
lang: "en"
author: "Marc Beepath"
email: "marcbeep@gmail.com"
github: "marcbeep"
linkedin: "marcbeep"
youtube: "@MarcsFieldnotes"

# SEO Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap # Generates a sitemap.xml for search engines
  - jekyll-feed # Creates an RSS feed for blog updates

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Marc Beepath"
      comments: false
      share: true
      keywords: "software engineering, AI, fintech, startups, technology, personal blog"
